"""Generate recipes/<package>/recipe.yaml for each entry in filters.yaml.

Each upstream repository is a Quarto extension. Its
_extensions/.../_extension.yml names the filter files
(contributes.filters) and declares two keys for packagers:

  pandoc-required: ">=3.1.1"            # becomes run constraints on both engines
  pandoc-test: pandoc lua spec/run.lua  # run from the repository root

The recipe installs each filter to $PREFIX/share/pandoc/filters, and its
test copies the installed filter over the repository's own copy and runs
pandoc-test, so upstream's suite tests the file we ship.

rattler-build can't read the source while rendering a recipe, hence this
generator. Usage:

  python scripts/gen-recipes.py          # write the recipes
  python scripts/gen-recipes.py --check  # fail if any recipe is out of date
"""

import argparse
import hashlib
import io
import posixpath
import sys
import tarfile
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
FILTERS_DIR = "share/pandoc/filters"


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def read_tarball(tarball):
    """Return the one _extension.yml (path in the repository, parsed yaml) and
    the repository's file tree as {path: is_symlink}."""
    found, tree = [], {}
    with tarfile.open(fileobj=io.BytesIO(tarball)) as tar:
        for m in tar.getmembers():
            # GitHub archives have one top-level directory, <repo>-<version>/.
            if "/" not in m.name:
                continue
            path = m.name.split("/", 1)[1]
            if m.isfile() or m.issym():
                tree[path] = m.issym()
            if path.startswith("_extensions/") and path.endswith("/_extension.yml"):
                found.append((path, yaml.safe_load(tar.extractfile(m))))
    if len(found) != 1:
        sys.exit(f"expected one _extensions/**/_extension.yml, found {[p for p, _ in found]}")
    return found[0], tree


def test_files(tree, prefix=""):
    """Globs for every file of the repository except symlinks, which conda
    can't create on Windows. A directory without symlinks is one glob."""
    children = {}
    for path, is_symlink in tree.items():
        if path.startswith(prefix):
            head, _, rest = path[len(prefix):].partition("/")
            children.setdefault(head, {})[rest] = is_symlink
    globs = []
    for name, sub in sorted(children.items()):
        if "" in sub:  # a file
            if not sub[""]:
                globs.append(prefix + name)
        elif not any(sub.values()):
            globs.append(f"{prefix}{name}/**")
        else:
            globs += test_files(tree, f"{prefix}{name}/")
    return globs


def recipe(package, entry):
    repo, tag = entry["repo"], entry["tag"]
    version = tag.removeprefix("v")
    url = f"https://github.com/{repo}/archive/refs/tags/{tag}.tar.gz"
    tarball = fetch(url)
    (ext_path, ext), tree = read_tarball(tarball)
    ext_dir = posixpath.dirname(ext_path)

    if str(ext.get("version")) != version:
        sys.exit(f"{package}: {ext_path} says version {ext.get('version')}, tag is {tag}")
    filters = [f if isinstance(f, str) else f["path"] for f in ext.get("contributes", {}).get("filters", [])]
    if not filters:
        sys.exit(f"{package}: {ext_path} contributes no filters")
    sources = [posixpath.join(ext_dir, f) for f in filters]
    names = [posixpath.basename(f) for f in filters]
    required = ext.get("pandoc-required")
    test = ext.get("pandoc-test")

    lines = [
        f"# Generated by scripts/gen-recipes.py from filters.yaml and {repo}@{tag}:{ext_path}.",
        "# Do not edit; change filters.yaml or upstream and regenerate.",
        "context:",
        f"  version: \"{version}\"",
        f"  build_number: {entry['build']}",
        "",
        "package:",
        f"  name: {package}",
        "  version: ${{ version }}",
        "",
        "source:",
        f"  url: {url}",
        f"  sha256: {hashlib.sha256(tarball).hexdigest()}",
        "",
        "build:",
        "  number: ${{ build_number }}",
        "  noarch: generic",
        "  string: pandoc_forge_${{ build_number }}",
        "  script:",
        f"    - mkdir -p $PREFIX/{FILTERS_DIR}",
        *(f"    - install -m 644 {s} $PREFIX/{FILTERS_DIR}/{n}" for s, n in zip(sources, names)),
        "",
        "requirements:",
        "  run:",
        "    - pandoc-api ${{ pandoc_api }}.*",
    ]
    if required:
        # A Lua filter runs inside pandoc, so its minimum is a pandoc version;
        # run constraints check whichever engine is installed without
        # installing one.
        lines += [
            "  run_constraints:",
            f"    - pandoc {required}",
            f"    - pandoc-wasm {required}",
        ]
    lines += [
        "",
        "tests:",
        "  - package_contents:",
        "      files:",
        *(f"        - {FILTERS_DIR}/{n}" for n in names),
    ]
    if test:
        lines += [
            "  # Upstream's own suite, against the installed filter.",
            "  - files:",
            "      source:",
            *(f"        - {g}" for g in test_files(tree)),
            "    requirements:",
            "      run:",
            "        - pandoc",
            "    script:",
            *(f"      - cp $PREFIX/{FILTERS_DIR}/{n} {s}" for s, n in zip(sources, names)),
            f"      - {test}",
        ]
    lines += [
        "",
        "about:",
        f"  homepage: https://github.com/{repo}",
        f"  repository: https://github.com/{repo}",
        f"  license: {entry['license']}",
        "  license_file: LICENSE",
        f"  summary: {entry['summary']}",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if a recipe is out of date")
    args = parser.parse_args()

    entries = yaml.safe_load((ROOT / "filters.yaml").read_text())
    stale = []
    for package, entry in entries.items():
        path = ROOT / "recipes" / package / "recipe.yaml"
        text = recipe(package, entry)
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        sys.exit(f"out of date, run scripts/gen-recipes.py: {', '.join(stale)}")


if __name__ == "__main__":
    main()
